version: '3.8'

services:
  app:
    build: ./backend
    container_name: app
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network

  php:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://db_user:db_password@db:3306/db_name
    depends_on:
      - db
    expose:
      - 8080
    ports:
      - "8080:8080"

  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network



networks:
  app-network:
    driver: bridge

volumes:
  db_data:
